language: cpp
dist: bionic
compiler: gcc
os:
  - linux
branches:
  only:
    - master
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - sudo apt update
  - sudo apt upgrade -y
  - sudo apt install build-essential g++-8 gcc-8 cmake libsnappy-dev -y
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake DCMAKE_BUILD_TYPE=Release -DBuildWithLevelDB=ON ../
  - cmake --build . -- -j 16